version: "3.8"

networks:
  tic-tac-backend-network:
    name: tic-tac-backend-network
    driver: bridge

services:

  tic-tac-backend:
    build:
      context: ./backend-new
      dockerfile: Dockerfile
    restart: always
    networks:
      - tic-tac-backend-network
    ports:
      - "8081:8081"
    expose:
      - "8081"
  
  tic-tac-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - tic-tac-backend-network
    ports:
      - "3000:3000"
    expose:
      - "3000"